# Generated by Django 5.1.3 on 2024-11-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('foto_perfil', models.FileField(upload_to='')),
                ('endereco', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackEstudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_resposta', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.estudantes')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFuncionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_resposta', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.cursos')),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fequencia_data', models.DateTimeField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.cursos')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.materias')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacoesEstudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.estudantes')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacoesFuncionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioAusenciaEstudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ausencia_data', models.CharField(max_length=255)),
                ('ausencia_mensagem', models.TextField()),
                ('ausencia_status', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.estudantes')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioAusenciaFuncionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ausencia_data', models.CharField(max_length=255)),
                ('ausencia_mensagem', models.TextField()),
                ('ausencia_status', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFrequencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.estudantes')),
                ('frequencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_estudantes.frequencia')),
            ],
        ),
    ]
