# Generated by Django 5.1.3 on 2024-11-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciamento_estudantes', '0003_delete_admin_remove_estudantes_curso_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('inep', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('rg', models.CharField(max_length=150)),
                ('ra', models.CharField(max_length=150)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.escola')),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='AdminEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=150)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presenca', models.BooleanField(default=False)),
                ('justificativa', models.TextField(blank=True, max_length=500, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nota_max', models.DecimalField(decimal_places=4, max_digits=6)),
                ('data', models.DateField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.materias')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(decimal_places=4, max_digits=6)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.alunos')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.avaliacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=150)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.escola')),
            ],
        ),
        migrations.AddField(
            model_name='materias',
            name='professores',
            field=models.ManyToManyField(related_name='materias', to='gerenciamento_estudantes.professores'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.professores'),
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.escola')),
            ],
        ),
        migrations.AddField(
            model_name='materias',
            name='turma',
            field=models.ManyToManyField(related_name='materias', to='gerenciamento_estudantes.turmas'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.turmas'),
        ),
    ]
