# Generated by Django 5.1.3 on 2024-11-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_estudantes', '0006_adminescola_usuario_alunos_usuario_escola_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='responsavel',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.responsavel'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='turma',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamento_estudantes.turmas'),
        ),
    ]
